"""empty message

Revision ID: 7cb99dfc51a6
Revises: 672651feea31
Create Date: 2023-10-06 20:31:52.334244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb99dfc51a6'
down_revision: Union[str, None] = '672651feea31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_tasks', sa.Column('text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_tasks', 'text')
    # ### end Alembic commands ###
