"""empty message

Revision ID: 7fc7c4bce430
Revises: a830bf82b070
Create Date: 2023-11-23 13:19:14.053898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc7c4bce430'
down_revision: Union[str, None] = 'a830bf82b070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_tasks', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('goal_tasks', 'completed')
    op.add_column('snapshot_tasks', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('snapshot_tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('snapshot_tasks', 'status')
    op.add_column('goal_tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('goal_tasks', 'status')
    # ### end Alembic commands ###
