"""empty message

Revision ID: 7fc7c4bce430
Revises: a830bf82b070
Create Date: 2023-11-23 13:19:14.053898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc7c4bce430'
down_revision: Union[str, None] = 'a830bf82b070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add the 'status' column as nullable
    op.add_column(
        'goal_tasks', sa.Column('status', sa.String(), nullable=True)
    )
    op.add_column(
        'snapshot_tasks', sa.Column('status', sa.String(), nullable=True)
    )

    # Step 2: Populate the 'status' column with a default value for existing records
    op.execute(
        "UPDATE goal_tasks SET status = 'NOT_STARTED' WHERE status IS NULL"
    )
    op.execute(
        "UPDATE snapshot_tasks SET status = 'NOT_STARTED' WHERE status IS NULL"
    )

    # Step 3: Alter the 'status' column to be non-nullable
    op.alter_column('goal_tasks', 'status', nullable=False)
    op.alter_column('snapshot_tasks', 'status', nullable=False)

    # Step 4: Drop the old 'completed' column
    op.drop_column('goal_tasks', 'completed')
    op.drop_column('snapshot_tasks', 'completed')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'snapshot_tasks',
        sa.Column(
            'completed', sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('snapshot_tasks', 'status')
    op.add_column(
        'goal_tasks',
        sa.Column(
            'completed', sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('goal_tasks', 'status')
    # ### end Alembic commands ###
