"""empty message

Revision ID: 9b822f3d16d9
Revises: 
Create Date: 2023-10-06 06:35:30.599473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b822f3d16d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_updates_id'), 'task_updates', ['id'], unique=False)
    op.drop_index('ix_task_progress_id', table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_column('tasks', 'goal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('task_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_progress_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_progress_pkey')
    )
    op.create_index('ix_task_progress_id', 'task_progress', ['id'], unique=False)
    op.drop_index(op.f('ix_task_updates_id'), table_name='task_updates')
    op.drop_table('task_updates')
    # ### end Alembic commands ###
