from alembic import op
import sqlalchemy as sa
from typing import Union, Sequence


# revision identifiers, used by Alembic.
revision: str = '9ea3c7102bf0'
down_revision: Union[str, None] = 'c98345383089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_templates') as batch_op:
        table = batch_op.get_context().reflect_table('goal_templates')
        if 'use_todays_date' not in table.columns:
            batch_op.add_column(
                sa.Column(
                    'use_todays_date',
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.true(),
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_templates') as batch_op:
        table = batch_op.get_context().reflect_table('goal_templates')
        if 'use_todays_date' in table.columns:
            batch_op.drop_column('use_todays_date')
    # ### end Alembic commands ###
