"""snapshot goal tasks lokked move to common

Revision ID: 9ea3c7102bf0
Revises: c98345383089
Create Date: 2023-12-27 18:56:36.091153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea3c7102bf0'
down_revision: Union[str, None] = 'c98345383089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'goal_templates',
        sa.Column(
            'use_todays_date',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_templates', 'use_todays_date')
    # ### end Alembic commands ###
