from alembic import op
from sqlalchemy.sql import text
import sqlalchemy as sa
from typing import Union, Sequence
from app.utils.alembic import column_exists

# revision identifiers, used by Alembic.
revision: str = '9ea3c7102bf0'
down_revision: Union[str, None] = 'c98345383089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('goal_templates', 'use_todays_date', op.get_bind()):
        op.add_column(
            'goal_templates',
            sa.Column(
                'use_todays_date',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            ),
        )
    else:
        op.alter_column(
            'goal_templates',
            'use_todays_date',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('goal_templates', 'use_todays_date', op.get_bind()):
        op.alter_column(
            'goal_templates',
            'use_todays_date',
            existing_type=sa.Boolean(),
            nullable=True,
            server_default=None,
        )
    else:
        op.drop_column('goal_templates', 'use_todays_date')
    # ### end Alembic commands ###
