"""relation snapshot and goals

Revision ID: a830bf82b070
Revises: c35b3ee8cfdb
Create Date: 2023-11-12 10:39:16.413522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a830bf82b070'
down_revision: Union[str, None] = 'c35b3ee8cfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_goals', sa.Column('board_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'snapshot_goals', 'board_snapshots', ['board_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snapshot_goals', type_='foreignkey')
    op.drop_column('snapshot_goals', 'board_id')
    # ### end Alembic commands ###
