"""todays date

Revision ID: c98345383089
Revises: d6b8ce57543c
Create Date: 2023-12-16 11:15:11.767406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98345383089'
down_revision: Union[str, None] = 'd6b8ce57543c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # remove the previous column if it exists
    # pass connection as 1st arg

    op.add_column(
        'goal_templates',
        sa.Column(
            'use_todays_date',
            sa.Boolean(),
            nullable=False,
            default=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_templates', 'use_todays_date')
    # ### end Alembic commands ###
