"""empty message
Revision ID: cc8edf381251
Revises: d98a1a5898ab
Create Date: 2023-10-09 05:57:56.268825
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cc8edf381251'
down_revision: Union[str, None] = 'd98a1a5898ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add 'notes' column as nullable without any default values
    op.add_column('goals', sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'notes')
    # ### end Alembic commands ###
