"""tasks_locked

Revision ID: d6b8ce57543c
Revises: a1c28f04cf0b
Create Date: 2023-12-03 15:25:37.891144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b8ce57543c'
down_revision: Union[str, None] = 'a1c28f04cf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable initially
    op.add_column(
        'goals', sa.Column('tasks_locked', sa.Boolean(), nullable=True)
    )

    # Set a default value for existing rows
    op.execute(
        'UPDATE goals SET tasks_locked = False WHERE tasks_locked IS NULL'
    )

    # Alter the column to not nullable
    op.alter_column(
        'goals', 'tasks_locked', existing_type=sa.Boolean(), nullable=False
    )

    # For 'snapshot_goals' table
    op.add_column(
        'snapshot_goals',
        sa.Column('tasks_locked', sa.Boolean(), nullable=True),
    )
    op.execute(
        'UPDATE snapshot_goals SET tasks_locked = False WHERE tasks_locked IS'
        ' NULL'
    )
    op.alter_column(
        'snapshot_goals',
        'tasks_locked',
        existing_type=sa.Boolean(),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'tasks_locked')
    # ### end Alembic commands ###

    # For 'snapshot_goals' table
    op.drop_column('snapshot_goals', 'tasks_locked')
