"""empty message

Revision ID: fe8270c27f7a
Revises: 2a4eacf400fe
Create Date: 2023-11-11 15:48:40.455041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8270c27f7a'
down_revision: Union[str, None] = '2a4eacf400fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'goals',
        sa.Column(
            'archived', sa.Boolean(), nullable=False, server_default='false'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'archived')
    # ### end Alembic commands ###
