version: '3'
services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=liblifedb
    volumes:
      - liblifedb:/var/lib/postgresql/data
  api:
    build:
      context: ./api
    ports:
      - '8999:8999'
    depends_on:
      - db
    environment:
      - DB_HOST=db
    volumes:
      - ./api:/api
      - pipcache:/root/.cache/pip
    command: sh -c "sed -i 's/localhost/db/g' alembic.ini && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8999 --reload"
  frontend:
    build:
      context: ./frontend
    ports:
      - '3999:3999'
    depends_on:
      - api
    environment:
      - PORT=3999
      - API_URL=http://api:8999
      - HOST=0.0.0.0
    command: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./nginx/html:/var/www/html
      - npmcache:/root/.npm
  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '81:81'
    depends_on:
      - api
      - frontend
    volumes:
      - ./nginx/html:/var/www/html
volumes:
  liblifedb:
  pipcache:
  npmcache:
